# Generated by Django 3.1.6 on 2021-02-05 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='会議ID')),
                ('num_men', models.IntegerField(verbose_name='男性の人数')),
                ('num_women', models.IntegerField(verbose_name='女性の人数')),
                ('duration_men', models.TimeField(blank=True, null=True, verbose_name='男性の継続時間')),
                ('duration_women', models.TimeField(blank=True, null=True, verbose_name='女性の継続時間')),
                ('meeting_status', models.CharField(blank=True, max_length=25, verbose_name='会議ステータス')),
            ],
            options={
                'verbose_name_plural': '会議',
                'db_table': 'meeting',
            },
        ),
    ]
