# Generated by Django 3.1.6 on 2021-02-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False, verbose_name='会議ID')),
                ('num_men', models.IntegerField(null=True, verbose_name='男性の人数')),
                ('num_women', models.IntegerField(null=True, verbose_name='女性の人数')),
                ('duration_men', models.IntegerField(blank=True, null=True, verbose_name='男性の継続時間')),
                ('duration_women', models.IntegerField(blank=True, null=True, verbose_name='女性の継続時間')),
                ('meeting_status', models.CharField(blank=True, max_length=25, verbose_name='会議ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '会議',
                'verbose_name_plural': '会議',
                'db_table': 'meeting',
                'ordering': ['created_at'],
            },
        ),
    ]
