# Generated by Django 3.1.6 on 2021-02-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_name',
        ),
    ]
