FROM node:14 as build-stage

WORKDIR /app

COPY package*.json ./
COPY yarn.lock ./
RUN yarn install
COPY . ./
RUN yarn run prod-build

FROM nginx:1.19.0-alpine as production-stage

RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx/nginx.conf /etc/nginx/nginx.conf
