version: "3.7"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.development
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    working_dir: /usr/src/app/
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.development
    depends_on:
      - db
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    expose:
      - 80
    ports:
      - 1337:80
    volumes:
      - media_volume:/usr/src/app/mediafiles
    depends_on:
      - app
    links:
      - app
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./var/db/data:/var/lib/postgresql/data/
    env_file:
      - ./.env.development
  pgadmin4:
    image:  dpage/pgadmin4:latest
    volumes:
      - pgadmin4:/var/lib/pgadmin
    env_file:
      - ./.env.development
    ports:
      - 5555:80
    depends_on:
      - db
    links:
      - db

volumes:
  pgadmin4:
  static_volume:
  media_volume:
