FROM nginx:1.19.0-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.production.conf /etc/nginx/conf.d

ENV STATIC_HOME=/usr/src/app
RUN mkdir -p $STATIC_HOME && \
    mkdir $STATIC_HOME/staticfiles && \
    mkdir $STATIC_HOME/mediafiles

# copy static files
COPY ./staticfiles $STATIC_HOME/staticfiles


